gem "rspec", ">= 1.2.6"
gem "haml"
gem "json"
gem "hpricot"
gem "mime-types", :require_as => "mime/types"
gem "ruby-growl"
gem "activesupport", :require_as => "active_support"
gem "sishen-rtranslate"
gem "progressions-basepath", :require_as => "basepath"
gem "progressions-g", :require_as => "g"
gem "timer"
gem "serenity"
gem "ymdp_generator"
gem "ymdt"
gem "yrb"
gem "idiom"

bin_path "vendor/bin"