# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ymdp}
  s.version = "0.1.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Coleman"]
  s.date = %q{2010-01-24}
  s.description = %q{Framework for developing applications in the Yahoo! Mail Development Platform.}
  s.email = %q{progressions@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".base",
     ".document",
     ".gitignore",
     "Gemfile",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/data/app/assets/yrb/en-US/keys_en-US.pres",
     "features/data/app/views/layouts/application.html.haml",
     "features/data/app/views/page.html.haml",
     "features/data/config/config.yml",
     "features/data/config/content.yml",
     "features/data/config/jslint.js",
     "features/data/config/servers.yml",
     "features/step_definitions/ymdp_steps.rb",
     "features/support/env.rb",
     "features/ymdp.feature",
     "lib/ymdp.rb",
     "lib/ymdp/application.rb",
     "lib/ymdp/application_view.rb",
     "lib/ymdp/asset_tag_helper.rb",
     "lib/ymdp/base.rb",
     "lib/ymdp/commands/build.rb",
     "lib/ymdp/commands/generate.rb",
     "lib/ymdp/compiler/base.rb",
     "lib/ymdp/compiler/domains.rb",
     "lib/ymdp/compiler/git_helper.rb",
     "lib/ymdp/compiler/options.rb",
     "lib/ymdp/compiler/template.rb",
     "lib/ymdp/configuration/config.rb",
     "lib/ymdp/configuration/constants.rb",
     "lib/ymdp/generator/templates/javascript.js",
     "lib/ymdp/generator/templates/stylesheet.css",
     "lib/ymdp/generator/templates/translation.pres",
     "lib/ymdp/generator/templates/view.html.haml",
     "lib/ymdp/processor/compressor.rb",
     "lib/ymdp/processor/form_post.rb",
     "lib/ymdp/processor/validator.rb",
     "lib/ymdp/processor/w3c.rb",
     "lib/ymdp/support/file.rb",
     "lib/ymdp/tag_helper.rb",
     "lib/ymdp/tasks/keys.rake",
     "lib/ymdp/tasks/ymdp.rake",
     "spec/application_spec.rb",
     "spec/application_view_spec.rb",
     "spec/compiler_spec.rb",
     "spec/compiler_template_spec.rb",
     "spec/compressor_spec.rb",
     "spec/configuration_spec.rb",
     "spec/default_settings.rb",
     "spec/domains_spec.rb",
     "spec/file_spec.rb",
     "spec/git_helper_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/stubs.rb",
     "spec/validator_spec.rb",
     "spec/ymdp_base_spec.rb",
     "spec/ymdp_spec.rb",
     "ymdp.gemspec"
  ]
  s.homepage = %q{http://github.com/progressions/ymdp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Framework for developing applications in the Yahoo! Mail Development Platform}
  s.test_files = [
    "spec/application_spec.rb",
     "spec/application_view_spec.rb",
     "spec/compiler_spec.rb",
     "spec/compiler_template_spec.rb",
     "spec/compressor_spec.rb",
     "spec/configuration_spec.rb",
     "spec/default_settings.rb",
     "spec/domains_spec.rb",
     "spec/file_spec.rb",
     "spec/git_helper_spec.rb",
     "spec/spec_helper.rb",
     "spec/stubs.rb",
     "spec/validator_spec.rb",
     "spec/ymdp_base_spec.rb",
     "spec/ymdp_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.6"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-growl>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<sishen-rtranslate>, [">= 0"])
      s.add_runtime_dependency(%q<progressions-basepath>, [">= 0"])
      s.add_runtime_dependency(%q<progressions-g>, [">= 0"])
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_runtime_dependency(%q<timer>, [">= 0"])
      s.add_runtime_dependency(%q<serenity>, [">= 0"])
      s.add_runtime_dependency(%q<ymdp_generator>, [">= 0"])
      s.add_runtime_dependency(%q<ymdt>, [">= 0"])
      s.add_runtime_dependency(%q<yrb>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.6"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0"])
      s.add_dependency(%q<ruby-growl>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<sishen-rtranslate>, [">= 0"])
      s.add_dependency(%q<progressions-basepath>, [">= 0"])
      s.add_dependency(%q<progressions-g>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<timer>, [">= 0"])
      s.add_dependency(%q<serenity>, [">= 0"])
      s.add_dependency(%q<ymdp_generator>, [">= 0"])
      s.add_dependency(%q<ymdt>, [">= 0"])
      s.add_dependency(%q<yrb>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.6"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0"])
    s.add_dependency(%q<ruby-growl>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<sishen-rtranslate>, [">= 0"])
    s.add_dependency(%q<progressions-basepath>, [">= 0"])
    s.add_dependency(%q<progressions-g>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<timer>, [">= 0"])
    s.add_dependency(%q<serenity>, [">= 0"])
    s.add_dependency(%q<ymdp_generator>, [">= 0"])
    s.add_dependency(%q<ymdt>, [">= 0"])
    s.add_dependency(%q<yrb>, [">= 0"])
  end
end

