#!/usr/bin/env ruby

BASE_PATH = "."
APP_DIR = "#{BASE_PATH}/app"
ASSETS_DIR = "#{APP_DIR}/assets"
VIEWS_DIR = "#{APP_DIR}/views"
JAVASCRIPTS_DIR = "#{APP_DIR}/javascripts"
STYLESHEETS_DIR = "#{APP_DIR}/stylesheets"

@view = ARGV[0]

puts "Destroying #{@view} view..."

system "git rm #{VIEWS_DIR}/#{@view}.html*"

system "git rm #{JAVASCRIPTS_DIR}/#{@view}.js"

system "git rm #{STYLESHEETS_DIR}/#{@view}.css"
