#!/usr/bin/env ruby

count = 0
used = []
unused = []

Dir["./app/assets/images/**/*"].each do |path|
  puts "Checking #{path}..."
  filename = path.split("/").last
  if filename =~ /(.*)\.(jpg|png|gif)$/
    puts "grep #{filename} ./servers/* -R"
    result = `grep #{filename} ./servers/* -R`
    print result
    if result.length < 1 || result =~ /Binary/
      puts "Adding #{path} to queue to remove..."
      unused << path
      # system "git rm #{path}"
    
      count += 1
    else
      used << path
    end
  end
end

puts "Counted #{count} unused files:."
unused.each do |file|
  puts file
end

if count > 0
  puts "Delete these files?"
  response = gets

  if response =~ /y/i
    unused.each do |file|
      system "git rm #{file}"
    end
  else
    puts "Cancelled."
  end

end

puts "The following #{used.size} files were used:"
used.each do |file|
  puts file
end
