#!/usr/bin/env ruby
status = `git status`

deleted_part = false

status.split("\n").each do |line|
  if line =~ /Changed but not updated/
    deleted_part ||= true
  end
  if deleted_part
    if line =~ /deleted: /
      filename = line.gsub("#	deleted:    ", "")
      puts filename
      system "git rm #{filename}"
    end
  end
end