#!/usr/bin/env ruby

require 'lib/init'

YMDP_ROOT = "."

include YMDP::Base

def keys(lang)
  path = "#{YMDP_ROOT}/servers/my/assets/yrb/keys_#{lang}.json"
  json = ""
  if File.exists?(path)
    File.open(path, "r") do |f|
      json = f.read
    end
  end
  <<-OUTPUT
Organizes low priority messages -- newsletters, coupons, promotions, receipts, etc into folders, which prioritizes email from real people in your Inbox, and summarizes it all in a digest so you don't miss anything important.
OUTPUT
  JSON.parse(json)
end

supported_languages.each do |lang|
  puts <<-OUTPUT
    <intl_strings intl="#{lang}">
      <name>#{keys(lang)["ORGANIZER"]}</name>
      <description>#{keys(lang)["DESCRIPTION"]}</description>
    </intl_strings>
    
OUTPUT
end